// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rcombszhlvafzpkfhooe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJjb21ic3pobHZhZnpwa2Zob29lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzMDY5MjcsImV4cCI6MjA2ODg4MjkyN30.KOreS5iaoH9MlTI5rt-lfu01vjQXKXRisPEUteGmTjo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});